#ifndef HELLO_WIFI_ESP_COMMANDS_H
#define HELLO_WIFI_ESP_COMMANDS_H

#include "esp_connection_data.h"

#define ESP_TEST "AT\r\n"
#define ESP_NO_ECHO "ATE0\r\n"
#define ESP_VERSION "AT+GMR\r\n"

#define ESP_WIFI_CLIENT "AT+CWMODE=1\r\n"
#define ESP_WIFI_CONNECT "AT+CWJAP=" DEFAULT_WIFI_NAME "," DEFAULT_WIFI_PASSWORD "\r\n"
#define ESP_GET_IP "AT+CIFSR\r\n"



#define ESP_TCP_CONNECT_TO_SERVER "AT+CIPSTART=\"TCP\",\"" DEFAULT_SERVER_IP "\"," DEFAULT_SERVER_PORT "\r\n"
#define ESP_PASSTHROUGH_MODE "AT+CIPMODE=1\r\n"
#define ESP_PASSTHROUGH_START "AT+CIPSEND\r\n"


#endif //HELLO_WIFI_ESP_COMMANDS_H
