#ifndef HELLO_WIFI_ESP_COMMANDS_H
#define HELLO_WIFI_ESP_COMMANDS_H

#include "esp_connection_data.h"

#define ESP_COMMAND_END "\r\n"

#define ESP_TEST "AT" ESP_COMMAND_END
#define ESP_NO_ECHO "ATE0" ESP_COMMAND_END
#define ESP_VERSION "AT+GMR" ESP_COMMAND_END

#define ESP_WIFI_CLIENT "AT+CWMODE=1" ESP_COMMAND_END
#define ESP_WIFI_CONNECT_BEGIN "AT+CWJAP=\""
#define ESP_WIFI_CONNECT_DELIMITER "\",\""
#define ESP_WIFI_CONNECT_END "\"" ESP_COMMAND_END
#define ESP_GET_IP "AT+CIFSR" ESP_COMMAND_END

#define ESP_TCP_CONNECT_TO_SERVER_BEGIN "AT+CIPSTART=\"TCP\",\""
#define ESP_TCP_CONNECT_TO_SERVER_DELIMITER "\","
#define ESP_TCP_CONNECT_TO_SERVER_END ESP_COMMAND_END

#define ESP_PASSTHROUGH_MODE "AT+CIPMODE=1" ESP_COMMAND_END
#define ESP_PASSTHROUGH_START "AT+CIPSEND" ESP_COMMAND_END

#endif //HELLO_WIFI_ESP_COMMANDS_H
