#ifndef DOCKERCONTROLSTM_ESP_CONNECTION_DATA_H
#define DOCKERCONTROLSTM_ESP_CONNECTION_DATA_H

// define default connection parameters here

#define DEFAULT_WIFI_NAME "R"
#define DEFAULT_WIFI_PASSWORD "Rigle_Da_3est#"

#define DEFAULT_SERVER_IP "192.168.1.253"
#define DEFAULT_SERVER_PORT "1500"

#endif //DOCKERCONTROLSTM_ESP_CONNECTION_DATA_H
