#ifndef DOCKERCONTROLSTM_DC_COMMANDS_H
#define DOCKERCONTROLSTM_DC_COMMANDS_H

#define PACKET_BEGIN '$'
#define PACKET_DELIMITER '!'
#define PACKET_END '#'


#define FOREACH_DC_COMMAND(DC_COMMAND) \
        DC_COMMAND(ACK)   \
        DC_COMMAND(CALL)  \
        DC_COMMAND(CATC)  \
        DC_COMMAND(CSTS)  \
        DC_COMMAND(CSTOP) \
        DC_COMMAND(CRST)  \
        DC_COMMAND(CRM)   \
        DC_COMMAND(CMK)   \
        DC_COMMAND(IALL)  \
        DC_COMMAND(STS)   \
        DC_COMMAND(ALRT)

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum DC_COMMAND_ENUM {
    FOREACH_DC_COMMAND(GENERATE_ENUM)
};

static const char *DC_COMMAND_STRING[] = {
    FOREACH_DC_COMMAND(GENERATE_STRING)
};


#endif //DOCKERCONTROLSTM_DC_COMMANDS_H
