#ifndef DOCKERCONTROLSTM_DC_COMMANDS_H
#define DOCKERCONTROLSTM_DC_COMMANDS_H

#define PACKET_BEGIN '$'
#define PACKET_DELIMITER '!'
#define PACKET_END '#'

#define FOREACH_DC_COMMAND(DC_COMMAND) \
        DC_COMMAND(READ) \
        DC_COMMAND(ACKN) \
        DC_COMMAND(CALL) \
        DC_COMMAND(CATC) \
        DC_COMMAND(CSTS) \
        DC_COMMAND(CSTP) \
        DC_COMMAND(CRST) \
        DC_COMMAND(CRMV) \
        DC_COMMAND(CMKI) \
        DC_COMMAND(IALL) \
        DC_COMMAND(SSTS) \
        DC_COMMAND(ALRT) \
        DC_COMMAND(ERRR)

#define GENERATE_ENUM(ENUM) ENUM,
#define GENERATE_STRING(STRING) #STRING,

enum DC_COMMAND_ENUM {
    FOREACH_DC_COMMAND(GENERATE_ENUM)
};

static const char *DC_COMMAND_STRING[] = {
    FOREACH_DC_COMMAND(GENERATE_STRING)
};

void dc_cmd_ready(const uint8_t * packet_header);

#endif //DOCKERCONTROLSTM_DC_COMMANDS_H
